"""
Script generation service — template-based, no external API required.

Each of the 7 finance categories has a dedicated script template with
parameterized slots. Scripts follow the structure:
    Hook -> Problem Statement -> Core Explanation -> Indian Rs Example -> CTA

Target: ~1800-2200 words ~= 9-11 minutes at 175 wpm TTS speed.
"""
from typing import Any, Dict, List

from src.config import CHANNEL_BRANDING, TTS_WORDS_PER_MINUTE
from src.utils.logger import get_logger

logger = get_logger(__name__)

# --------------- Tag bank ---------------

_TAG_BANK: Dict[str, List[str]] = {
    "Stock Market Basics": [
        "stock market for beginners", "nifty 50", "how to invest in stocks India",
        "equity investment", "trading basics", "stock market India 2025",
        "sensex", "share market", "long term investing",
    ],
    "Mutual Funds": [
        "mutual fund SIP", "best mutual funds India", "SIP investment",
        "mutual fund for beginners", "direct mutual fund", "equity mutual fund",
        "debt mutual fund", "mutual fund returns India", "ELSS tax saving",
    ],
    "Personal Finance": [
        "personal finance India", "money management", "financial planning",
        "how to save money", "emergency fund", "financial freedom India",
        "passive income India", "wealth building India",
    ],
    "Tax Planning": [
        "income tax India", "section 80C", "ITR filing", "tax saving tips India",
        "HRA exemption", "new tax regime", "old tax regime", "tax deductions India",
        "how to save tax in India",
    ],
    "Cryptocurrency": [
        "cryptocurrency India", "bitcoin India", "crypto investing 2025",
        "blockchain explained", "crypto tax India", "ethereum India",
        "altcoins India", "crypto for beginners",
    ],
    "Real Estate": [
        "real estate investment India", "property investment India", "REIT India",
        "rent vs buy India", "affordable housing", "property tax India",
        "real estate 2025", "housing market India",
    ],
    "Budgeting": [
        "budgeting tips India", "50 30 20 rule", "zero based budgeting",
        "how to manage money India", "expense tracker", "monthly budget India",
        "financial planning India", "save money India",
    ],
}

# --------------- Template definitions ---------------


def _template_stock_market(subtopic: str) -> Dict[str, Any]:
    title = f"{subtopic} | Complete Guide for Indian Investors"
    description = (
        f"In this video we break down everything you need to know about {subtopic}. "
        "Perfect for beginners and intermediate investors in India. "
        "Learn how to navigate the stock market, manage risk, and grow your wealth."
    )
    hook = (
        f"Welcome back to {CHANNEL_BRANDING}! If you have ever wondered how ordinary Indians"
        f" are building extraordinary wealth through the stock market, then you are in exactly"
        f" the right place today."
        f"\n\nToday we are diving deep into {subtopic}. Whether you are just getting started"
        f" with your first investment account or you want to sharpen your long-term strategy,"
        f" this video will give you a clear, practical, and completely actionable roadmap."
        f" No jargon, no confusing charts, no theories that only work in textbooks."
        f" By the end of today's video, you will know exactly what to do, what mistakes to avoid,"
        f" and how to build a system that works for Indian investors just like you."
        f"\n\nStay with me till the very end because I have a real rupee calculation that will"
        f" show you how much wealth a small monthly investment can actually create over time."
        f" And the numbers might genuinely surprise you. Let us get started right now."
    )
    problem = (
        f"Let me start with a number that should bother every single person watching this video."
        f"\n\nAccording to multiple financial surveys, more than 80 percent of Indian households"
        f" keep the majority of their savings in bank fixed deposits or savings accounts."
        f" Bank savings accounts in India currently offer around 3 to 4 percent interest per year."
        f" Fixed deposits offer approximately 6 to 7 percent per year for a standard one year term."
        f"\n\nNow here is the problem. India's average consumer price inflation has consistently"
        f" run at 5 to 7 percent per year over the last decade. That means if your money is"
        f" earning 4 percent in a savings account but inflation is 6 percent, your actual"
        f" purchasing power is going backwards by 2 percent every single year."
        f"\n\nAfter 10 years of this, your money has not just stood still. It has quietly lost"
        f" a significant portion of its real value, even though the nominal number in your"
        f" passbook looks bigger. This is called negative real returns, and it affects crores"
        f" of Indian families every year."
        f"\n\nThe solution is not complicated. But it does require understanding how the stock"
        f" market works, what {subtopic} really means in practice, and how to apply it in a"
        f" way that fits your income, your risk tolerance, and your financial goals."
        f"\n\nMost beginner resources available online are built for American or European"
        f" investors. They talk about the S and P 500, they give examples in dollars, and they"
        f" assume a financial infrastructure that simply does not exist in India. Today we are"
        f" going to fix all of that with a guide built specifically for {subtopic} in the"
        f" Indian context."
    )
    explanation = (
        f"Let us break down {subtopic} properly, starting from the absolute foundation."
        f"\n\nThe Indian stock market is primarily represented by two exchanges. The NSE, which"
        f" stands for National Stock Exchange, and the BSE, which stands for Bombay Stock"
        f" Exchange. The Nifty 50 index tracks the performance of the top 50 companies by"
        f" free-float market capitalisation on the NSE. The Sensex tracks the top 30 companies"
        f" on the BSE. When news says the market went up or down by 1 percent today, they are"
        f" almost always referring to the Nifty 50."
        f"\n\nWhen you buy a share of a company, you are buying a small fractional ownership"
        f" stake in that business. If the company grows its revenues and profits over time,"
        f" the value of your ownership stake grows. If the company pays dividends, you receive"
        f" a proportional share of those profits directly into your bank account."
        f"\n\nNow let us go deeper into {subtopic} with five concepts you must understand."
        f"\n\nConcept one is the difference between trading and investing. Trading means buying"
        f" and selling stocks frequently, trying to profit from short-term price movements."
        f" Investing means buying quality companies and holding them for years or decades,"
        f" allowing compounding to work. Research consistently shows that more than 90 percent"
        f" of retail traders lose money. Long-term investors in quality indices and companies"
        f" have historically done very well. For {subtopic}, we are firmly in the investing"
        f" camp, not the trading camp."
        f"\n\nConcept two is understanding market cycles. The stock market does not go up in"
        f" a straight line. It goes through bull markets, which are extended periods of rising"
        f" prices, and bear markets, which are periods of falling prices of 20 percent or more"
        f" from recent highs. India has experienced major bear markets in 2001, 2008, 2015,"
        f" and 2020. Every single time, the market eventually recovered and reached new highs."
        f" The investors who stayed invested through those crashes were rewarded. The ones who"
        f" sold in panic locked in permanent losses."
        f"\n\nConcept three is the role of diversification. Never put all your money in a"
        f" single stock or a single sector. If you invest only in IT stocks and the IT sector"
        f" underperforms for 3 years, your entire portfolio suffers. But if you hold a"
        f" diversified portfolio across banking, IT, healthcare, FMCG, infrastructure, and"
        f" manufacturing, underperformance in one sector is offset by others."
        f"\n\nConcept four is the difference between large cap, mid cap, and small cap stocks."
        f" Large cap stocks are the top 100 companies by market capitalisation. They are the"
        f" most stable, the most liquid, and carry the lowest risk. Think Reliance, TCS, HDFC"
        f" Bank, Infosys. Mid cap stocks are companies ranked 101 to 250. They have higher"
        f" growth potential but more volatility. Small cap stocks are companies ranked 251 and"
        f" beyond. They can deliver spectacular returns but also spectacular losses. As a"
        f" beginner, start with large cap index funds before moving to mid and small cap."
        f"\n\nConcept five, and this is the most powerful one, is the time value of money"
        f" combined with compounding. Compounding means your returns earn returns. A 12 percent"
        f" annual return does not just add 12 percent each year to your initial investment."
        f" It adds 12 percent to the growing total each year. Over 20 or 30 years, this creates"
        f" wealth that is mathematically difficult to believe until you actually see the numbers."
        f"\n\nHow to get started with {subtopic} in India."
        f" Step one: Open a DEMAT and trading account with a SEBI-registered discount broker."
        f" Zerodha, Groww, and Upstox are popular, low-cost options with zero account opening fees."
        f" Step two: Complete your KYC using Aadhaar and PAN. This takes 10 to 15 minutes online."
        f" Step three: Start with an index fund SIP rather than individual stocks."
        f" Step four: Invest an amount you can afford to leave untouched for a minimum of 5 years."
        f" Step five: Automate your investments so they happen without needing your willpower each month."
    )
    example = (
        f"Let me give you a real Indian rupee example that makes all of this completely concrete."
        f"\n\nPriya is a 28 year old software engineer in Pune earning a take-home salary of"
        f" 70,000 rupees per month. She has been keeping her savings in a fixed deposit at"
        f" 6.5 percent per year. After learning about {subtopic}, she decides to redirect"
        f" 10,000 rupees per month into a Nifty 50 index fund through a monthly SIP."
        f"\n\nLet us look at what happens under different time horizons. The Nifty 50 has"
        f" delivered approximately 13 to 15 percent CAGR over 20 year rolling periods"
        f" historically. We will use a conservative 12 percent assumption."
        f"\n\nMonthly SIP: 10,000 rupees."
        f" Total invested over 10 years: 12 lakh rupees."
        f" Corpus after 10 years at 12 percent: approximately 23.2 lakh rupees."
        f"\n\nTotal invested over 20 years: 24 lakh rupees."
        f" Corpus after 20 years at 12 percent: approximately 99.9 lakh rupees, close to 1 crore."
        f"\n\nTotal invested over 30 years: 36 lakh rupees."
        f" Corpus after 30 years at 12 percent: approximately 3.5 crore rupees."
        f"\n\nSo Priya invested a total of 36 lakh rupees over 30 years and ended up with"
        f" 3.5 crore rupees. Her money multiplied nearly 10 times over the total amount she"
        f" put in. The magic here is not a high salary or a genius stock pick. It is just"
        f" consistency, time, and the mathematical miracle of compounding."
        f"\n\nNow compare that with the fixed deposit approach. The same 10,000 rupees per"
        f" month at 6.5 percent per year over 30 years would give a corpus of approximately"
        f" 1.1 crore rupees. That is a 2.4 crore rupee difference from the same amount of"
        f" money, simply by choosing {subtopic} over a fixed deposit."
        f"\n\nBut here is an important nuance. The stock market comes with volatility. In year"
        f" 8 of Priya's investment, the Nifty might fall 35 percent during a crisis. Her"
        f" portfolio value drops temporarily. But because she keeps her monthly SIP running,"
        f" she is actually buying more units at lower prices during the crash. When the market"
        f" recovers, those cheap units generate outsized returns. This strategy is called rupee"
        f" cost averaging, and it is one of the great advantages of a SIP investment approach."
        f"\n\nOne final scenario to motivate you. If Priya had started the same 10,000 rupee"
        f" SIP 5 years earlier, at age 23, the 30 year corpus would grow to approximately"
        f" 6.4 crore rupees instead of 3.5 crore rupees. Five extra years of investing created"
        f" 2.9 crore rupees of additional wealth. This is why starting early is so critically important."
    )
    cta = (
        f"Let me give you your complete action plan for {subtopic} to implement this week."
        f"\n\nAction step one: If you do not have a DEMAT account, open one today. Go to Zerodha,"
        f" Groww, or Upstox and complete the online KYC. It genuinely takes less than 20 minutes"
        f" and there is no cost involved."
        f"\n\nAction step two: Decide your monthly SIP amount. Start with whatever is comfortable."
        f" Even 500 rupees per month is a start. The habit and the account are more important"
        f" than the amount when you are beginning."
        f"\n\nAction step three: Choose a Nifty 50 index fund as your first investment."
        f" Good options include UTI Nifty 50 Index Fund Direct Growth or HDFC Index Fund Nifty"
        f" 50 Plan Direct Growth. Both have very low expense ratios below 0.15 percent per year."
        f"\n\nAction step four: Set up an auto-debit mandate through your net banking so the SIP"
        f" amount deducts automatically every month without requiring any action from you."
        f"\n\nAction step five: Commit to a 5 year minimum horizon. Do not check your portfolio"
        f" value every day. Set a quarterly calendar reminder for a 5 minute review and that is all."
        f"\n\nAction step six: As your income grows, increase your SIP amount. Even increasing"
        f" by 10 percent per year makes an enormous difference to your final corpus over 20 to"
        f" 30 years."
        f"\n\nThat is your complete roadmap for {subtopic}. The knowledge you now have is worth"
        f" crores of rupees over your investing lifetime."
        f"\n\nIf this video helped you understand {subtopic} more clearly, please hit the like"
        f" button right now. It takes one second and it genuinely helps our channel reach more"
        f" Indians who need this information."
        f"\n\nSubscribe to {CHANNEL_BRANDING} for a brand new finance video every single day"
        f" of the week. Drop your questions in the comments section below. I personally read"
        f" every single comment and respond to as many as I possibly can."
        f"\n\nUntil next time, invest smart, stay consistent, and let the power of compounding"
        f" do the heavy lifting for you. I will see you in tomorrow's video."
    )
    sections = {"hook": hook, "problem": problem, "explanation": explanation,
                "example": example, "cta": cta}
    return {"title": title, "description": description, "sections": sections}


def _template_mutual_funds(subtopic: str) -> Dict[str, Any]:
    title = f"{subtopic} | Everything You Need to Know"
    description = (
        f"This video covers {subtopic} in complete detail from basics to advanced strategies "
        "for Indian investors. Learn how mutual funds work, which types suit your goals, "
        "and how to get started today with as little as 500 rupees."
    )
    hook = (
        f"What if I told you that there is a way to invest in hundreds of companies"
        f" simultaneously, with as little as 500 rupees per month, managed by professional"
        f" fund managers who spend their entire working lives analysing businesses, all without"
        f" you needing any knowledge of how to pick stocks?"
        f"\n\nThat is exactly what mutual funds offer. And today on {CHANNEL_BRANDING}, we are"
        f" covering {subtopic} from the very beginning to the advanced level."
        f"\n\nThis video is for you if you have heard about mutual funds but are not completely"
        f" sure how they work. It is for you if you have already started investing but want to"
        f" make sure you are doing it right. And it is absolutely for you if you have been"
        f" putting this off because it felt too complicated."
        f"\n\nI promise you, by the time we finish today, {subtopic} will feel completely clear"
        f" and manageable. Stay with me till the end because I have a real rupee example that"
        f" will show you the staggering difference that starting early versus starting late"
        f" makes to your retirement corpus. The numbers are genuinely life-changing."
    )
    problem = (
        f"Here is the situation that millions of educated, intelligent, hardworking Indians"
        f" find themselves in every single year."
        f"\n\nThey know they should be investing. They have heard about mutual funds. They may"
        f" have even downloaded an investing app. But they have not started yet, or they started"
        f" and then stopped, because the options feel overwhelming."
        f"\n\nShould you choose equity or debt? Large cap or mid cap? Direct or regular? Growth"
        f" or dividend? SIP or lump sum? The number of choices is paralysing, and most people"
        f" end up making no decision at all. Or worse, they take advice from a bank relationship"
        f" manager who steers them toward high-commission regular plans that eat into their"
        f" returns for years."
        f"\n\nThere is also a second problem. Many people who have been investing for years are"
        f" doing so in inefficient ways. They might be in regular plans instead of direct plans,"
        f" losing 0.5 to 1 percent of returns every year to distributor commissions. Over 20"
        f" years, that difference compounds into lakhs of rupees of lost wealth."
        f"\n\n{subtopic} is the key that unlocks clarity in all of this. Let me give you the"
        f" complete picture."
    )
    explanation = (
        f"Let us build a solid understanding of {subtopic} from first principles."
        f"\n\nA mutual fund is a pooled investment vehicle. Thousands of investors contribute"
        f" money into a common fund. A professional fund manager uses that pooled money to buy"
        f" a diversified portfolio of assets according to a specific stated investment objective."
        f" The NAV, which stands for Net Asset Value, represents the per-unit value of the fund"
        f" on any given day. When the underlying investments go up in value, the NAV rises."
        f" When they fall, it falls."
        f"\n\nThere are several broad categories of mutual funds you need to know for {subtopic}."
        f"\n\nEquity mutual funds invest primarily in stocks. They are designed for long-term"
        f" wealth creation, typically 5 years or more, and carry higher short-term volatility."
        f" Within equity funds, there are multiple subcategories."
        f" Large cap funds invest in the top 100 companies. These are the most stable equity"
        f" funds with historical returns of approximately 12 to 14 percent annually over long periods."
        f" Mid cap funds invest in companies ranked 101 to 250. More volatile but higher growth potential."
        f" Small cap funds invest in companies ranked 251 and beyond. High risk, high reward."
        f" Flexi cap and multi cap funds give the fund manager freedom to invest across all categories."
        f" ELSS funds, or Equity Linked Saving Schemes, are equity funds with a 3 year lock-in"
        f" period that also provide a tax deduction under Section 80C up to 1.5 lakh rupees per year."
        f" Index funds passively track an index like Nifty 50 or Nifty 500. They have no active"
        f" management, which means extremely low costs and historically strong long-term returns."
        f"\n\nDebt mutual funds invest in government securities, corporate bonds, and money market"
        f" instruments. They are lower risk and suitable for short-term goals of 1 to 3 years."
        f" Returns are typically 6 to 9 percent annually, better than savings accounts but lower"
        f" than long-term equity returns."
        f"\n\nHybrid funds combine equity and debt in different proportions. Conservative hybrid"
        f" funds are roughly 25 percent equity and 75 percent debt. Aggressive hybrid funds are"
        f" the reverse. These are good for moderate risk investors who want some equity upside"
        f" with some stability."
        f"\n\nNow, the single most important concept for {subtopic} that most people get wrong."
        f"\n\nDirect plans versus regular plans."
        f" Every mutual fund in India comes in two versions. The regular plan includes a"
        f" distributor commission that is paid from your invested money every year. This reduces"
        f" your returns. The direct plan has no distributor commission. You invest directly through"
        f" the AMC or a direct platform. The expense ratio on direct plans is typically 0.5 to"
        f" 1.2 percent lower per year than regular plans."
        f"\n\nOn a 1 lakh rupee investment over 20 years at 12 percent, that 1 percent difference"
        f" in expense ratio results in a difference of approximately 2.4 lakh rupees in final"
        f" corpus. Always choose direct plans."
        f"\n\nSIP versus lump sum for {subtopic}."
        f" A SIP, or Systematic Investment Plan, is an automated monthly investment of a fixed"
        f" amount. It gives you the benefit of rupee cost averaging. When markets fall, your fixed"
        f" rupee amount buys more units. When markets rise, it buys fewer. Over time, your average"
        f" cost per unit is lower than the average market price, which improves returns. SIPs also"
        f" remove the psychological challenge of trying to time the market."
        f"\n\nA lump sum investment works well if you have a large amount ready and markets are"
        f" at a reasonable valuation. For most people, however, SIP is the better approach because"
        f" it is disciplined, automatic, and works with any income level."
    )
    example = (
        f"Let me walk you through a real Indian example that makes the power of {subtopic}"
        f" completely vivid."
        f"\n\nWe have two people: Rahul, who starts investing at 25, and Amit, who waits until 35."
        f" Both invest the same 5,000 rupees per month. Both earn the same 13 percent annual"
        f" return in their equity mutual funds. Both stop investing at age 60 when they retire."
        f"\n\nRahul starts at 25: 35 years of SIP."
        f" Total invested: 5,000 multiplied by 12 months multiplied by 35 years equals 21 lakh rupees."
        f" Final corpus at age 60: approximately 3.2 crore rupees."
        f"\n\nAmit starts at 35: 25 years of SIP."
        f" Total invested: 5,000 multiplied by 12 months multiplied by 25 years equals 15 lakh rupees."
        f" Final corpus at age 60: approximately 95 lakh rupees."
        f"\n\nRahul ends up with 3.2 crore rupees. Amit ends up with 95 lakh rupees."
        f" Rahul invested only 6 lakh rupees more than Amit, but he has 2.25 crore rupees more"
        f" in retirement wealth. That is the cost of 10 years of waiting."
        f"\n\nNow let us look at the direct versus regular plan comparison using the same numbers."
        f" If Amit had invested his 5,000 rupees per month in a regular plan with a 1.2 percent"
        f" higher expense ratio, his 95 lakh corpus would instead be approximately 78 lakh rupees."
        f" The 17 lakh rupee difference went silently to distributors over 25 years."
        f"\n\nFor {subtopic}, here is a simple beginner portfolio that works extremely well."
        f" Allocation one: 50 percent into a Nifty 50 index fund. This gives you stability and"
        f" broad market exposure at the lowest possible cost."
        f" Allocation two: 30 percent into a flexi cap or mid cap fund for additional growth potential."
        f" Allocation three: 20 percent into ELSS for tax saving under Section 80C."
        f"\n\nTotal monthly SIP starting at 500 rupees for each category means you begin with"
        f" 1,500 rupees per month. As your income grows, scale all three proportionally."
        f" Review your portfolio once every 6 months. Rebalance once per year if your allocation"
        f" has drifted by more than 10 percentage points from your targets. That is all the"
        f" maintenance this portfolio needs."
    )
    cta = (
        f"Here is exactly what to do in the next 24 hours for {subtopic}."
        f"\n\nStep one: Choose your platform. Groww, Kuvera, and Paytm Money all offer direct"
        f" mutual fund plans with zero commission. Avoid bank relationship managers who push"
        f" regular plans."
        f"\n\nStep two: Complete your KYC if you have not already. You need your PAN card and"
        f" Aadhaar for the EKYC process. It takes 10 to 15 minutes and is a one-time requirement."
        f"\n\nStep three: Select your first fund. For absolute beginners, the UTI Nifty 50 Index"
        f" Fund Direct Growth or Mirae Asset Large Cap Fund Direct Growth are excellent starting points."
        f"\n\nStep four: Start your first SIP. Even 500 rupees per month is a real start."
        f" The habit is more important than the amount when you are beginning. You can always"
        f" increase it later."
        f"\n\nStep five: Set up auto-debit from your savings account so the SIP amount deducts"
        f" automatically every month on the 5th or 10th. You will never miss it once it is automated."
        f"\n\nStep six: Ignore the NAV fluctuations for at least the next 12 months. The short-term"
        f" volatility is completely normal and is actually your friend if you are investing regularly."
        f"\n\nThat is your complete roadmap for {subtopic}. If you implement just these six steps,"
        f" you will be ahead of 80 percent of Indian investors by next week."
        f"\n\nPlease like this video if it gave you clarity. Share it with one person in your"
        f" family who has been putting off starting their investment journey. You could genuinely"
        f" change someone's financial future today."
        f"\n\nSubscribe to {CHANNEL_BRANDING} for new finance education content every single day."
        f" I will see you in tomorrow's video. Invest well!"
    )
    sections = {"hook": hook, "problem": problem, "explanation": explanation,
                "example": example, "cta": cta}
    return {"title": title, "description": description, "sections": sections}


def _template_personal_finance(subtopic: str) -> Dict[str, Any]:
    title = f"{subtopic} | Practical Money Guide for Indians"
    description = (
        f"Learn about {subtopic} with actionable steps designed for the Indian middle class. "
        "Real rupee examples, zero jargon, and strategies you can implement this week."
    )
    hook = (
        f"A financial survey published last year found that 78 percent of Indians cannot cover"
        f" an unexpected expense of 50,000 rupees without borrowing money or selling an asset."
        f" That is not a small number. That is more than three out of every four people you know."
        f"\n\nAnd here is the most important part of that finding. The problem is not income."
        f" Many of the people surveyed earned salaries above 80,000 or even 1 lakh rupees per"
        f" month. The problem is the absence of a conscious, structured financial system."
        f"\n\nToday on {CHANNEL_BRANDING}, I am going to give you that system. We are covering"
        f" {subtopic}, which is one of the most foundational topics in building lasting personal wealth."
        f"\n\nI am going to show you exactly why most people struggle financially regardless of"
        f" how much they earn, and then I am going to walk you through a step-by-step system"
        f" designed specifically for Indian incomes and Indian expense patterns. Real strategies."
        f" Real rupee numbers. Actionable from today. Let us begin."
    )
    problem = (
        f"Let me describe the financial life of the average Indian professional very precisely."
        f"\n\nOn the first or fifth of the month, the salary arrives. There is a brief moment"
        f" of feeling wealthy. Then the EMIs deduct automatically. Rent goes. Groceries are"
        f" bought. A few impulse purchases happen because the salary just arrived and the mood"
        f" is good. A dinner out here, a purchase on Amazon there. By the 20th of the month,"
        f" the mood shifts. Money is getting tight. By the 28th, there is active waiting for"
        f" the next salary. By the month end, the account balance is down to a few hundred or"
        f" a few thousand rupees."
        f"\n\nThe net savings for the month: zero or close to it."
        f"\n\nSound familiar? If it does, you are not alone and you are not bad with money."
        f" You are simply operating without a system. And here is the uncomfortable truth that"
        f" no one tells you. Your spending is not the problem. Your system is the problem."
        f" The human brain is not naturally wired to plan finances optimally. We are wired to"
        f" respond to immediate rewards and to spend what is available. Without deliberate"
        f" systems that override our defaults, we will always spend up to our income level."
        f" This phenomenon is called lifestyle inflation, and it affects everyone from people"
        f" earning 30,000 rupees per month to those earning 3 lakh per month."
        f"\n\n{subtopic} is exactly the system that fixes this. And once you have the system"
        f" in place, managing money actually becomes easier, not harder. Let me show you how."
    )
    explanation = (
        f"Let us build the complete framework for {subtopic} step by step."
        f"\n\nThe foundational principle, and this is the one that changes everything, is called"
        f" Pay Yourself First. Most people earn money, pay all their bills and expenses, and"
        f" then save whatever is left over at the end of the month. The problem with this"
        f" approach is that there is almost always nothing left. Lifestyle expands to fill the"
        f" available budget. Pay Yourself First flips this completely. You decide on your savings"
        f" and investment amount upfront. You transfer that amount the moment your salary arrives,"
        f" before paying anything else. Then you live on what remains. This single change, more"
        f" than any other habit, separates people who build wealth from people who stay stuck financially."
        f"\n\nThe second component of {subtopic} is understanding and categorising your cash flow."
        f" Most people have no clear picture of where their money actually goes. They have a vague"
        f" sense that they spend on rent, food, and some shopping, but they cannot tell you the"
        f" exact numbers. The first step to improving anything is measuring it. Track every single"
        f" rupee you spend for 30 days. Use a budgeting app, your UPI transaction history, or a"
        f" simple spreadsheet. Most people are shocked when they see the breakdown. Food delivery"
        f" apps like Swiggy and Zomato often account for 6,000 to 10,000 rupees per month without"
        f" people realising it. Subscriptions that are never used continue silently charging each month."
        f"\n\nThe third component is the allocation framework. The most practical framework for"
        f" {subtopic} in India is a modified version of the 50-30-20 rule."
        f"\n\n50 percent of take-home income goes to genuine needs. This includes rent or home"
        f" loan EMI, groceries, utilities, insurance premiums, transport to work, and EMIs on"
        f" essential purchases. If your needs cost more than 50 percent of your income, that is"
        f" your most urgent financial signal that either your income needs to increase or your"
        f" fixed commitments need to be restructured."
        f"\n\n30 percent goes to wants. This is money for dining out, entertainment, hobbies,"
        f" travel, clothing beyond basics, and lifestyle upgrades. This bucket does not need to"
        f" be eliminated. It just needs to be bounded. Knowing you have 30 percent budgeted for"
        f" enjoyment removes the guilt from spending on things you enjoy."
        f"\n\n20 percent goes to your future. This is your most important bucket. It covers your"
        f" emergency fund contribution, SIP investments, additional loan repayments, and insurance"
        f" premiums if not already in the needs category."
        f"\n\nThe fourth component of {subtopic} is building your emergency fund before everything else."
        f" An emergency fund is a cash reserve of 3 to 6 months of essential expenses. If your"
        f" essential monthly expenses are 40,000 rupees, your target emergency fund is 1.6 to"
        f" 2.4 lakh rupees. This should be kept in a high-yield savings account or liquid mutual"
        f" fund where you can access it within 24 hours. Not in a fixed deposit that has a penalty"
        f" for early withdrawal. Until your emergency fund is fully built, every rupee of your"
        f" 20 percent future bucket should go there first."
        f"\n\nThe fifth component is the debt elimination hierarchy. If you carry any high-interest"
        f" debt, it must be treated as a financial emergency. Credit card debt in India carries"
        f" 36 to 48 percent annual interest. Personal loans typically carry 14 to 20 percent."
        f" No investment in the stock market can consistently beat a 40 percent guaranteed return"
        f" from eliminating a credit card balance. Once your emergency fund is funded, direct all"
        f" extra money toward debt elimination, starting with the highest interest rate first."
    )
    example = (
        f"Let me show you {subtopic} in action through a real example with real numbers."
        f"\n\nMeet Anjali. She is a 32 year old HR manager in Mumbai with a take-home salary of"
        f" 80,000 rupees per month. On paper, she earns a comfortable income. In practice, she"
        f" has zero savings, a credit card outstanding of 1.4 lakh rupees at 42 percent annual"
        f" interest, and no investments."
        f"\n\nHere is her current monthly breakdown before applying {subtopic}."
        f" Rent: 22,000 rupees."
        f" Groceries and household supplies: 9,000 rupees."
        f" Food delivery and eating out: 8,500 rupees."
        f" Credit card EMI minimum payment: 7,000 rupees."
        f" Shopping, clothing, Amazon: 10,000 rupees."
        f" Streaming services and subscriptions: 2,800 rupees."
        f" Petrol and Ola Uber: 5,500 rupees."
        f" Miscellaneous and impulse spending: 15,200 rupees."
        f" Total: 80,000 rupees. Net savings: zero."
        f"\n\nNow here is Anjali's plan after implementing {subtopic}."
        f"\n\nMonth one to month three, her primary goal is clearing the credit card debt"
        f" aggressively. She applies the 50-30-20 rule strictly."
        f" Needs, 50 percent, equals 40,000 rupees: rent 22,000, groceries 9,000, transport"
        f" 5,000, utilities 4,000."
        f" Wants, 10 percent, equals 8,000 rupees: she dramatically cuts dining and shopping"
        f" for three months because clearing debt at 42 percent interest is her emergency."
        f" Future, 40 percent, equals 32,000 rupees: this entire amount goes to credit card"
        f" payoff each month for three months."
        f"\n\nAfter three months: 96,000 rupees paid toward the credit card. Debt of 1.4 lakh"
        f" rupees is now cleared completely. She also saved 7,000 rupees per month in interest charges."
        f"\n\nMonth four to month nine, her goal is building the emergency fund."
        f" Needs: 40,000 rupees."
        f" Wants: 16,000 rupees, now normalised."
        f" Future: 24,000 rupees, entirely toward the emergency fund."
        f"\n\nAfter six months: 1.44 lakh rupees in an emergency liquid fund."
        f"\n\nMonth ten onwards, with debt eliminated and emergency fund in place, Anjali"
        f" redirects her entire future bucket to wealth building."
        f" SIP into Nifty 50 index fund: 12,000 rupees per month."
        f" SIP into ELSS for tax saving: 8,000 rupees per month."
        f" RD for next vacation or large purchase: 4,000 rupees per month."
        f"\n\nAt this pace, Anjali invests 20,000 rupees per month. At 12 percent returns over"
        f" 25 years, this grows to approximately 3.9 crore rupees by age 57. All from the same"
        f" 80,000 rupee salary that previously produced zero savings."
        f"\n\nSame income. Different system. Completely different financial future."
        f" That is the power of {subtopic} done right."
    )
    cta = (
        f"Here is your 5-step action plan to implement {subtopic} starting today, not tomorrow."
        f"\n\nStep one: Pull up your last three months of bank statements and UPI transaction"
        f" history right now. Add up how much you spent in each major category. Just seeing"
        f" the numbers is transformative. Most people discover at least 5,000 to 10,000 rupees"
        f" of spending they cannot recall or justify."
        f"\n\nStep two: Open a separate savings account specifically for your emergency fund"
        f" if you do not have one. Open it at a different bank from your salary account to"
        f" create a small psychological barrier to easy spending. Transfer whatever you can"
        f" today, even if it is just 1,000 rupees, to start the habit."
        f"\n\nStep three: Set up an automatic transfer for 20 percent of your salary, to be"
        f" debited on the day after salary credit. This is your Pay Yourself First automation."
        f"\n\nStep four: Write down all your outstanding debts, the balance on each, and the"
        f" interest rate. Identify your highest interest rate debt. This is your target."
        f"\n\nStep five: Use the first three months purely to build momentum. Clear some debt."
        f" Start the emergency fund. Begin the 50-30-20 tracking. Do not worry about optimising"
        f" everything perfectly from day one. Starting imperfectly is infinitely better than"
        f" planning perfectly and never beginning."
        f"\n\n{subtopic} is not complicated. It is just a system. And systems, once set up,"
        f" run on autopilot. That is exactly how you want your money to work."
        f"\n\nIf this video helped you see your finances differently, please like it and share"
        f" it with someone in your life who is in that paycheck to paycheck cycle."
        f"\n\nSubscribe to {CHANNEL_BRANDING} for daily finance education. See you tomorrow!"
    )
    sections = {"hook": hook, "problem": problem, "explanation": explanation,
                "example": example, "cta": cta}
    return {"title": title, "description": description, "sections": sections}


def _template_tax_planning(subtopic: str) -> Dict[str, Any]:
    title = f"{subtopic} | Save More Tax Legally in India"
    description = (
        f"Complete guide to {subtopic} for Indian taxpayers. Understand your options, "
        "maximize your deductions, and keep more of your hard-earned money all legally."
    )
    hook = (
        f"Here is a question I want you to think about seriously. If your employer transferred"
        f" an extra 46,800 rupees directly into your bank account every single year, would you"
        f" notice? Of course you would. That is 3,900 rupees every month, which is a significant"
        f" amount for most Indian households."
        f"\n\nNow here is the thing. That money is already yours. The Indian government created"
        f" legal deductions and exemptions that allow you to keep exactly that much more of your"
        f" own earnings. But most salaried employees never claim it fully because no one"
        f" explained the system to them in simple language."
        f"\n\nToday on {CHANNEL_BRANDING}, we are covering {subtopic} completely. I am going to"
        f" show you every major legal deduction available to Indian taxpayers, how to calculate"
        f" exactly which tax regime saves you more money, and what specific actions to take"
        f" before the end of this financial year."
        f"\n\nStay with me to the end because I have a side-by-side calculation using real rupee"
        f" numbers that will show you precisely how much you could be saving. Let us get into it."
    )
    problem = (
        f"Let me describe what happens to the average salaried Indian employee's tax situation."
        f"\n\nIn January or February, the HR department sends an email asking for investment"
        f" proofs. Most employees scramble to find receipts and submit whatever documents they"
        f" have. Some maximise their Section 80C. Most do not. Very few know about the other"
        f" deductions available to them. The result is that the tax deducted at source, or TDS,"
        f" from their salary throughout the year is significantly higher than it legally needs to be."
        f"\n\nAt the end of the financial year, many people file ITR, wait for a refund, and"
        f" feel slightly relieved when it arrives. But they rarely stop to ask: was the refund"
        f" as large as it should have been? Am I using every legal deduction available to me?"
        f"\n\nThe problem is not greed. It is lack of knowledge. The Income Tax Act of India"
        f" contains hundreds of sections. New rules are added or modified in every Budget. And"
        f" the advice most people get from family, colleagues, or even their own chartered"
        f" accountants is generic at best."
        f"\n\n{subtopic} is about taking the time once a year to understand your specific"
        f" situation, compare your options, and make informed choices that legally minimise your"
        f" tax burden. This is not tax evasion. Evasion is illegal. This is tax planning, which"
        f" is not just legal but is explicitly encouraged by the government through the very"
        f" provisions they created."
    )
    explanation = (
        f"Let us build a complete understanding of {subtopic} with everything you need to know."
        f"\n\nIndia currently has two income tax regimes, and choosing the right one is the"
        f" single most important tax decision for most salaried employees."
        f"\n\nThe New Tax Regime has lower tax slab rates but eliminates most deductions."
        f" The Old Tax Regime has higher rates but allows a rich set of deductions and exemptions."
        f"\n\nTax slabs under the New Regime for Financial Year 2025 to 2026."
        f" Income up to 3 lakh rupees: zero tax."
        f" Income from 3 to 7 lakh rupees: 5 percent."
        f" Income from 7 to 10 lakh rupees: 10 percent."
        f" Income from 10 to 12 lakh rupees: 15 percent."
        f" Income from 12 to 15 lakh rupees: 20 percent."
        f" Income above 15 lakh rupees: 30 percent."
        f" Important note: a standard deduction of 75,000 rupees is available under the new regime."
        f" Also: under Section 87A, if your total taxable income is 7 lakh rupees or below,"
        f" your tax liability is completely zero under the new regime."
        f"\n\nTax slabs under the Old Regime."
        f" Income up to 2.5 lakh rupees: zero."
        f" Income from 2.5 to 5 lakh rupees: 5 percent."
        f" Income from 5 to 10 lakh rupees: 20 percent."
        f" Income above 10 lakh rupees: 30 percent."
        f" The old regime allows a large number of deductions that significantly reduce your"
        f" taxable income before these slab rates apply."
        f"\n\nThe key deductions under the Old Regime."
        f"\n\nSection 80C, with a combined limit of 1.5 lakh rupees per year. This is the most"
        f" widely used deduction. Qualifying instruments include Employee Provident Fund"
        f" contributions, Public Provident Fund, ELSS mutual funds, life insurance premiums,"
        f" home loan principal repayment, NSC, Sukanya Samriddhi Yojana, and children's tuition"
        f" fees. Most salaried employees already hit this limit through EPF alone, so topping"
        f" up with PPF or ELSS is straightforward."
        f"\n\nSection 80CCD 1B for NPS contributions: an additional deduction of up to 50,000"
        f" rupees per year beyond the Section 80C limit. This is separate from and in addition"
        f" to 80C. If you contribute 50,000 rupees to NPS, this reduces your taxable income by"
        f" that amount regardless of what you have already claimed under 80C."
        f"\n\nSection 80D for health insurance premiums: up to 25,000 rupees for premiums paid"
        f" for yourself, spouse, and children. An additional 25,000 rupees if your parents are"
        f" below 60 years old, or 50,000 rupees if your parents are senior citizens. Total"
        f" potential deduction: 75,000 rupees. This also covers preventive health check-ups"
        f" up to 5,000 rupees."
        f"\n\nHRA exemption for employees receiving House Rent Allowance who live in rented"
        f" accommodation. The exempt amount is calculated as the minimum of three values:"
        f" actual HRA received, 50 percent of basic salary for metros or 40 percent for"
        f" non-metros, and actual rent paid minus 10 percent of basic salary."
        f"\n\nSection 24 b for home loan interest: up to 2 lakh rupees per year can be deducted"
        f" for interest paid on a home loan for a self-occupied property."
        f"\n\nNow the critical question for {subtopic}: which regime saves you more?"
        f" The general rule is: if your eligible deductions total less than approximately"
        f" 2.5 to 3.5 lakh rupees, the new regime saves you money. If your eligible deductions"
        f" exceed 3.75 lakh rupees, the old regime usually wins. For incomes below 7 lakh rupees,"
        f" the new regime with zero tax under 87A is almost always better. For incomes above"
        f" 15 lakh rupees with significant deductions, run the actual comparison. The Income Tax"
        f" portal at incometax.gov.in has a free regime comparison calculator."
    )
    example = (
        f"Let me walk you through {subtopic} with a concrete comparison using real numbers."
        f"\n\nVikram is a software engineer in Hyderabad earning a gross CTC of 14 lakh rupees"
        f" per year. His basic salary is 6 lakh rupees per year. His HRA component is 3 lakh"
        f" rupees per year. He pays 18,000 rupees per month in rent, which is 2.16 lakh rupees annually."
        f"\n\nHere is his Old Regime calculation with smart {subtopic}."
        f" Gross salary: 14,00,000 rupees."
        f" Standard deduction: minus 50,000."
        f" HRA exemption: rent paid minus 10 percent of basic equals 2,16,000 minus 60,000"
        f" equals 1,56,000 rupees."
        f" Section 80C: EPF contribution approximately 72,000 plus PPF top up of 78,000:"
        f" total 1,50,000."
        f" Section 80CCD 1B NPS: 50,000 rupees."
        f" Section 80D health insurance: 25,000 rupees for self and family."
        f" Total deductions: 50,000 plus 1,56,000 plus 1,50,000 plus 50,000 plus 25,000"
        f" equals 4,31,000."
        f" Taxable income: 14,00,000 minus 4,31,000 equals 9,69,000."
        f" Old regime tax on 9,69,000: approximately 1,17,500 rupees."
        f" After 4 percent health and education cess: approximately 1,22,200 rupees."
        f"\n\nHere is his New Regime calculation."
        f" Gross salary: 14,00,000 rupees."
        f" Standard deduction: minus 75,000."
        f" Taxable income: 13,25,000 rupees."
        f" New regime tax: approximately 1,65,000 rupees."
        f" After 4 percent cess: approximately 1,71,600 rupees."
        f"\n\nOld regime saves Vikram: 1,71,600 minus 1,22,200 equals 49,400 rupees per year."
        f"\n\nThat is close to 4,100 rupees every month in additional take-home pay just from"
        f" applying {subtopic} correctly. And the investments he made to claim 80C and NPS"
        f" deductions are building his long-term wealth simultaneously. This is the double"
        f" benefit of smart tax planning."
    )
    cta = (
        f"Here is your complete tax action checklist for implementing {subtopic} this year."
        f"\n\nAction one: Run the old versus new regime comparison for your specific income and"
        f" deductions using the free calculator on the Income Tax India portal at incometax.gov.in."
        f" This takes 15 minutes and could be worth thousands of rupees."
        f"\n\nAction two: Maximise Section 80C if you are in the old regime. If your EPF"
        f" contributions do not already reach 1.5 lakh, top up with PPF contributions by"
        f" March 31st. If you want equity exposure with tax benefits, add ELSS mutual fund SIP."
        f"\n\nAction three: Open an NPS Tier 1 account if you do not have one. Contribute 50,000"
        f" rupees per year to claim the additional 80CCD 1B deduction. This is over and above"
        f" your 80C limit."
        f"\n\nAction four: Buy comprehensive health insurance for yourself and your parents if"
        f" you have not already done so. This serves two purposes: it protects your family from"
        f" catastrophic medical costs and gives you an 80D deduction of up to 75,000 rupees annually."
        f"\n\nAction five: Submit your investment declarations to your HR team well before the"
        f" February deadline. Last-minute submissions often mean the deductions cannot be"
        f" processed correctly and you end up with a much larger TDS shortfall."
        f"\n\nAction six: File your ITR before the July 31st deadline. Do not wait for the"
        f" last day. File early, check your Form 26AS for correct TDS credit, and verify your AIS."
        f"\n\n{subtopic} is one of the highest return on investment activities you can do with"
        f" your time. An hour spent understanding your tax situation can save you 30,000 to"
        f" 60,000 rupees."
        f"\n\nPlease share this video with your colleagues. Most salaried employees are overpaying"
        f" tax right now because of simple gaps in knowledge. This video could fix that for someone."
        f"\n\nSubscribe to {CHANNEL_BRANDING} for daily finance education. See you in the next video!"
    )
    sections = {"hook": hook, "problem": problem, "explanation": explanation,
                "example": example, "cta": cta}
    return {"title": title, "description": description, "sections": sections}


def _template_crypto(subtopic: str) -> Dict[str, Any]:
    title = f"{subtopic} | What Indian Investors Must Know"
    description = (
        f"A balanced, educational guide to {subtopic} for Indian audiences. "
        "Understand the technology, risks, regulations, and how to approach "
        "crypto responsibly as part of a diversified portfolio."
    )
    hook = (
        f"India now has more than 100 million cryptocurrency investors, making it one of the"
        f" largest crypto user bases in the entire world. Bitcoin has crossed price levels that"
        f" were considered impossible just a few years ago. Ethereum, Solana, and dozens of"
        f" other cryptocurrencies have made headlines with both spectacular gains and devastating crashes."
        f"\n\nAnd yet, most Indian crypto investors are operating with incomplete information."
        f" They know the asset went up. They know it went down. But they do not fully understand"
        f" what they own, how the underlying technology works, what the Indian regulatory and"
        f" tax framework looks like, or how to size a crypto position responsibly within a"
        f" broader financial plan."
        f"\n\nToday on {CHANNEL_BRANDING}, we are giving you a complete, honest, and balanced"
        f" deep dive into {subtopic}. No hype, no fear. Just the facts and frameworks you need"
        f" to make informed decisions."
        f"\n\nBy the end of this video, you will understand exactly what to do, what to avoid,"
        f" and how to approach crypto in a way that protects your overall financial wellbeing."
        f" Let us begin."
    )
    problem = (
        f"Let me tell you two contrasting true stories that represent the extremes of the"
        f" crypto experience in India."
        f"\n\nStory one. In 2020, a young engineer in Bengaluru invested 2 lakh rupees in"
        f" Bitcoin when it was trading at approximately 7 lakh rupees per coin. He held through"
        f" the volatility. By late 2021, his investment had grown to over 20 lakh rupees."
        f" He understood the risks, sized his position correctly, and had a plan to exit a"
        f" portion at target levels."
        f"\n\nStory two. A salaried professional in Chennai borrowed 8 lakh rupees through a"
        f" personal loan in early 2021, invested it all in a mix of altcoins following influencer"
        f" recommendations, and watched the portfolio crash 85 percent within 18 months. He"
        f" ended up with 1.2 lakh rupees of portfolio value against an 8 lakh rupee loan that"
        f" was still accumulating 18 percent annual interest."
        f"\n\nThe difference between these two outcomes was not luck. It was knowledge, position"
        f" sizing, and risk management. The first investor understood {subtopic}. The second"
        f" one did not. Today we make sure you have everything you need to be in the first category."
    )
    explanation = (
        f"Let us build a thorough understanding of {subtopic} from first principles."
        f"\n\nWhat is cryptocurrency? A cryptocurrency is a digital or virtual asset that uses"
        f" cryptography to secure transactions, control the creation of new units, and verify"
        f" the transfer of assets. Unlike the Indian rupee, which is issued and controlled by"
        f" the Reserve Bank of India, most cryptocurrencies operate on decentralised networks"
        f" with no single controlling authority."
        f"\n\nHow blockchain technology works. Blockchain is the foundational technology"
        f" underlying most cryptocurrencies. It is a distributed ledger, meaning the same"
        f" record of all transactions is stored simultaneously on thousands of computers around"
        f" the world. When a transaction is initiated, it is broadcast to this network. Nodes,"
        f" which are the computers maintaining the network, verify the transaction through a"
        f" consensus mechanism and add it to a block. Each block is cryptographically linked to"
        f" the previous one, forming a chain. This structure makes it computationally impossible"
        f" to alter historical transactions without invalidating every subsequent block on the"
        f" entire network."
        f"\n\nThe key cryptocurrencies you need to understand for {subtopic}."
        f" Bitcoin, abbreviated as BTC, is the original cryptocurrency created in 2009. It has"
        f" a fixed maximum supply of 21 million coins, making it inherently deflationary."
        f" Bitcoin is primarily viewed as a store of value, similar in concept to digital gold."
        f" Its network is the most secure and most decentralised of all cryptocurrencies."
        f"\n\nEthereum, abbreviated as ETH, is a programmable blockchain that allows developers"
        f" to build applications called smart contracts and decentralised apps. It powers the"
        f" majority of decentralised finance protocols, NFT platforms, and Web3 applications."
        f"\n\nStablecoins such as USDT Tether and USDC are cryptocurrencies designed to maintain"
        f" a 1 to 1 peg with the US dollar. They are widely used for trading, transfers, and"
        f" accessing DeFi yield opportunities without exposure to crypto price volatility."
        f"\n\nThe Indian regulatory framework for {subtopic}."
        f" Cryptocurrency is completely legal to buy, sell, and hold in India. It is not banned."
        f" The Indian government has chosen regulation over prohibition. Cryptocurrency is not"
        f" legal tender in India. You cannot use it to pay for everyday goods."
        f" From a tax perspective as of 2025, gains from cryptocurrency transfers are taxed at"
        f" a flat 30 percent rate regardless of how long you held the asset. There is no benefit"
        f" for long-term holding unlike equity. Additionally, a 1 percent TDS is deducted at"
        f" source on cryptocurrency transactions above 50,000 rupees per year with a registered exchange."
        f" Losses from cryptocurrency transactions cannot be offset against any other income."
        f"\n\nExchange safety and regulation."
        f" Only use cryptocurrency exchanges that are registered with the Financial Intelligence"
        f" Unit of India. Registered exchanges comply with Know Your Customer and Anti-Money"
        f" Laundering requirements. Major registered Indian exchanges include CoinDCX, CoinSwitch,"
        f" ZebPay, and WazirX. Avoid unregistered foreign exchanges and anything that offers"
        f" guaranteed returns because no legitimate crypto investment does."
        f"\n\nRisk management framework for {subtopic}."
        f" Allocate no more than 5 to 10 percent of your total investment portfolio to cryptocurrency."
        f" If you are a beginner, start with Bitcoin only before exploring other cryptocurrencies."
        f" Never invest money you cannot afford to lose completely. Crypto markets can drop 80 to"
        f" 90 percent in bear markets. This has happened multiple times."
        f" Do not use leverage or borrowed money for crypto."
        f" Your 12 or 24 word seed phrase is the master key to your crypto. Never share it with"
        f" anyone. Never enter it on any website. Back it up on paper and store it securely offline."
    )
    example = (
        f"Let me show you how to apply {subtopic} practically with a real Indian investor scenario."
        f"\n\nKavya is a 30 year old graphic designer in Bangalore with a total investment"
        f" portfolio of 6 lakh rupees. She is interested in crypto and wants to allocate responsibly."
        f"\n\nHer current portfolio."
        f" Index funds and direct equity: 4 lakh rupees. About 67 percent of portfolio."
        f" Debt funds and FD: 1.5 lakh rupees. About 25 percent."
        f" Emergency fund in liquid fund: 50,000 rupees. Not counted as investment portfolio."
        f"\n\nFollowing the 5 to 10 percent crypto allocation rule for {subtopic}."
        f" Maximum responsible crypto allocation: 5 percent of 6 lakh equals 30,000 rupees."
        f" She decides on 30,000 rupees into Bitcoin only, purchased through CoinDCX with full KYC."
        f"\n\nTax implications she calculates upfront."
        f" If Bitcoin doubles and she sells: gain is 30,000 rupees."
        f" Tax at flat 30 percent: 9,000 rupees."
        f" Net gain after tax: 21,000 rupees."
        f"\n\nShe understands that the tax treatment makes crypto less tax-efficient than equity,"
        f" which benefits from long-term capital gains rates. For equity held more than 1 year,"
        f" gains above 1.25 lakh rupees are taxed at only 12.5 percent. Crypto gains are always"
        f" 30 percent."
        f"\n\nShe maintains a detailed record of her crypto transactions for ITR filing. Date of"
        f" purchase, price in rupees, amount of Bitcoin purchased, and all subsequent transactions."
        f" This record keeping is mandatory for accurate ITR filing."
        f"\n\nOne year later: Bitcoin has gone up 40 percent. Her 30,000 investment is now worth"
        f" 42,000. She does not sell in excitement. Her investment thesis was a long-term hold."
        f" The rest of her portfolio is unchanged. She reviews her total portfolio quarterly."
        f"\n\nThis is responsible {subtopic}: eyes open, risks understood, position sized"
        f" correctly, tax implications accounted for, and no emotional decisions based on price movements."
    )
    cta = (
        f"Here is the responsible framework for implementing {subtopic} as an Indian investor."
        f"\n\nRule one: Educate before you invest. Before buying any cryptocurrency, you should"
        f" be able to explain in one or two sentences what it does, why it has value, and what"
        f" could make it fail. If you cannot do this, do not invest yet."
        f"\n\nRule two: Allocate no more than 5 to 10 percent of your total investment portfolio"
        f" to crypto. Your core wealth should always be in equity index funds, debt instruments,"
        f" and real estate. Crypto is a high-risk, high-reward satellite position, not a core holding."
        f"\n\nRule three: Start with Bitcoin only. It is the most established, most liquid, and"
        f" most regulated cryptocurrency. Explore other assets only after you understand Bitcoin well."
        f"\n\nRule four: Use only FIU-IND registered Indian exchanges. Complete your KYC fully."
        f" Avoid anything that cannot tell you exactly who regulates them."
        f"\n\nRule five: Keep meticulous records of every transaction for income tax purposes."
        f" Every buy, every sell, every exchange, every transfer. The 30 percent flat tax makes"
        f" record keeping critical for accurate ITR filing."
        f"\n\nRule six: For any amount above 50,000 rupees held long term, move it off the"
        f" exchange to a hardware wallet where you control the private keys."
        f"\n\nRule seven: Never invest money you cannot afford to lose completely. Crypto markets"
        f" are genuinely volatile enough that this rule is not a formality. It is a real risk."
        f"\n\nCrypto can be a legitimate part of a diversified portfolio when approached with"
        f" full knowledge and appropriate risk management. That is exactly what {subtopic} enables."
        f"\n\nIf this video added clarity for you, please share it with someone who has been"
        f" asking you about crypto lately. This could save them from making a very expensive mistake."
        f"\n\nSubscribe to {CHANNEL_BRANDING} for daily finance education. See you in the next video!"
    )
    sections = {"hook": hook, "problem": problem, "explanation": explanation,
                "example": example, "cta": cta}
    return {"title": title, "description": description, "sections": sections}


def _template_real_estate(subtopic: str) -> Dict[str, Any]:
    title = f"{subtopic} | Smart Property Decisions for Indians"
    description = (
        f"Everything you need to know about {subtopic} from an Indian investor's perspective. "
        "From analysing rental yields to understanding REITs, this video gives you the full picture."
    )
    hook = (
        f"Owning property is the deepest financial aspiration for most Indian families. Every"
        f" parent wants to leave a house for their children. Every young professional dreams of"
        f" the day they will stop paying rent. Real estate is woven into our cultural identity"
        f" as a marker of success and security."
        f"\n\nBut is buying property always the smartest financial decision? And if you want"
        f" real estate exposure in your investment portfolio without purchasing a physical"
        f" property, what options do you actually have in India today?"
        f"\n\nToday on {CHANNEL_BRANDING}, we are going to answer both of those questions with"
        f" absolute clarity. We are covering {subtopic} in complete detail, including the numbers"
        f" most real estate promoters would prefer you never see."
        f"\n\nThis video is for anyone who has ever asked whether they should buy a home or keep"
        f" renting, for anyone who is thinking about property as an investment, and for anyone"
        f" who has heard about REITs but is not sure what they are or whether they are worth"
        f" investing in. I am going to give you the complete picture. Stay till the end."
    )
    problem = (
        f"Let me describe the most expensive financial mistake that millions of Indian families"
        f" make every single decade."
        f"\n\nA young couple in Pune, both earning well, decides to buy a flat. The property"
        f" costs 85 lakh rupees. They take a home loan at 9 percent interest for 20 years."
        f" The EMI is approximately 76,500 rupees per month. They are excited. This is the dream."
        f"\n\nWhat most people do not calculate at the time of purchase."
        f" The total interest paid over 20 years on an 85 lakh loan at 9 percent is approximately"
        f" 1.01 crore rupees. They will pay 1.86 crore rupees in total for an 85 lakh rupee property."
        f" Before we even account for the down payment, registration fees, stamp duty, maintenance"
        f" charges, society fees, repairs, and property tax."
        f"\n\nStamp duty and registration: approximately 5 to 6 percent of property value, which"
        f" is 4.25 to 5.1 lakh rupees as a one-time cost paid upfront."
        f" Annual maintenance and society charges: 12,000 to 36,000 rupees per year."
        f" Minor repairs and modifications over 20 years: typically 3 to 8 lakh rupees."
        f"\n\nIf the property appreciates at the national average of 5 to 7 percent annually,"
        f" its value after 20 years would be approximately 2.7 to 3.3 crore rupees. Sounds"
        f" impressive until you subtract the total cost of ownership."
        f"\n\nThis is not an argument against buying property. It is an argument for making an"
        f" informed, calculated decision rather than an emotional one. {subtopic} gives you the"
        f" tools to do that."
    )
    explanation = (
        f"Let us build a thorough framework for {subtopic} with everything you need to make"
        f" smart real estate decisions in India."
        f"\n\nUnderstanding real estate returns in the Indian context."
        f" Average residential property appreciation across major Indian cities from 2015 to"
        f" 2025 has ranged from 4 to 8 percent annually in most tier-1 cities, with Hyderabad"
        f" and Bengaluru being notable outperformers in certain micro-markets at 8 to 12 percent"
        f" annually. Tier-2 cities have seen more modest appreciation of 3 to 6 percent."
        f"\n\nRental yield, which is the annual rental income as a percentage of property value,"
        f" is consistently low in India. In Mumbai, Delhi, Bangalore, and Pune, residential"
        f" rental yields typically range from 1.5 to 3 percent. Compare this to commercial"
        f" properties, which can yield 7 to 9 percent annually."
        f"\n\nThe Price-to-Rent ratio is one of the most important metrics for {subtopic}."
        f" It is calculated as property purchase price divided by annual rental income."
        f" A price to rent ratio of 15 or below generally favours buying. Above 20 generally"
        f" favours renting and investing. In India's major cities, the price to rent ratio for"
        f" residential property commonly ranges from 25 to 40 or higher."
        f"\n\nFor {subtopic}, the rent versus buy decision should consider these factors."
        f"\n\nHow long do you plan to stay in the city? If less than 7 years, renting almost"
        f" always wins financially because the transaction costs of buying amount to 8 to 12"
        f" percent of property value and take years to recover."
        f"\n\nWhat is your career stage and income stability? If there is a meaningful chance"
        f" you will relocate for career growth within the next 5 years, tying yourself to a"
        f" property is a significant constraint. Rented accommodation gives you mobility."
        f"\n\nWhat is the actual price-to-rent ratio in your target micro-market? Calculate it"
        f" for the specific area and property type you are considering. A 1 crore flat that"
        f" rents for 20,000 per month has a price-to-rent ratio of 1 crore divided by 2.4 lakh"
        f" annual rent, which equals approximately 42. This strongly favours renting and investing"
        f" the difference."
        f"\n\nWhat is your investment discipline? If you rent instead of buy, will you actually"
        f" invest the EMI difference every month? Or will it simply get spent on lifestyle?"
        f" Buying property creates forced savings. Many people genuinely need this discipline mechanism."
        f"\n\nREITs as an alternative for {subtopic}."
        f" Real Estate Investment Trusts, or REITs, are publicly listed investment vehicles that"
        f" own and operate income-generating commercial real estate. In India, REITs were"
        f" introduced by SEBI in 2019 and are listed on the NSE and BSE."
        f"\n\nHow REITs work: they pool money from investors to buy large commercial real estate"
        f" assets such as office parks, malls, and warehouses. At least 90 percent of distributable"
        f" cash flows must be distributed to unit holders as regular income."
        f"\n\nCurrently listed Indian REITs include Embassy Office Parks REIT, Mindspace Business"
        f" Parks REIT, and Brookfield India Real Estate Trust."
        f"\n\nWhy REITs are compelling for {subtopic}."
        f" Minimum investment of approximately 10,000 to 15,000 rupees per unit versus lakhs for"
        f" physical property. Quarterly distributions averaging 7 to 9 percent annual yield."
        f" Complete liquidity: you can sell your REIT units on the exchange in seconds."
        f" No maintenance costs, no tenant headaches, no legal title risks."
        f" Professional management of high-quality Grade A commercial properties."
        f" Diversification across multiple properties and tenants."
    )
    example = (
        f"Let me apply {subtopic} to a concrete scenario that many viewers will relate to directly."
        f"\n\nScenario: Arjun and Suresh are brothers, both 32 years old, both earning 1.2 lakh"
        f" rupees per month take-home salary, both living in Pune with the same family situation."
        f"\n\nArjun decides to buy a flat worth 80 lakh rupees."
        f" Down payment: 16 lakh rupees from savings."
        f" Home loan: 64 lakh rupees at 9 percent for 20 years."
        f" EMI: approximately 57,600 rupees per month."
        f" Stamp duty and registration paid: approximately 4.5 lakh rupees."
        f" Total upfront outflow: 20.5 lakh rupees."
        f"\n\nSuresh decides to rent a similar flat for 20,000 rupees per month and invest the difference."
        f" He invests the remaining 37,600 rupees per month into a diversified equity portfolio."
        f"\n\nAfter 20 years, let us look at both outcomes."
        f"\n\nArjun: Property has appreciated at 7 percent annually."
        f" 80 lakh purchased in 2025 is worth approximately 3.1 crore rupees in 2045."
        f" Total cost paid: 16 lakh down payment plus 4.5 lakh stamp duty plus 57,600 EMI times"
        f" 240 months equals approximately 1.38 crore rupees in EMIs."
        f" Total ownership cost: approximately 1.82 crore rupees."
        f" Net position: property worth 3.1 crore minus total cost 1.82 crore equals approximately"
        f" 1.28 crore rupees of net gain after 20 years."
        f"\n\nSuresh: Invested 37,600 rupees per month at a blended 12 percent annual return."
        f" Corpus after 20 years: approximately 3.7 crore rupees."
        f" He also paid 20,000 per month in rent for 20 years: total rent paid 48 lakh rupees."
        f" Net position after accounting for rent: 3.7 crore minus 48 lakh equals approximately"
        f" 3.22 crore rupees."
        f"\n\nSuresh is ahead by approximately 1.94 crore rupees assuming he actually invested"
        f" the difference consistently. However, if Suresh had lifestyle inflated and spent the"
        f" 37,600 instead of investing it, he would have zero assets. Arjun would have 3.1 crore"
        f" in property."
        f"\n\nThis is the honest picture of {subtopic}. The winner depends entirely on discipline."
        f" If you will invest the difference: renting wins financially in most Indian metro markets."
        f" If you will spend the difference: buying is the better forced savings mechanism."
    )
    cta = (
        f"Here is your decision framework and action plan for {subtopic}."
        f"\n\nIf you are evaluating buying a property."
        f"\n\nStep one: Calculate the price-to-rent ratio for the specific property. Divide"
        f" purchase price by annual rental income for that property. If it is above 25, the"
        f" financial case for buying is weak and renting plus investing is likely superior."
        f"\n\nStep two: Factor in all real costs. Add stamp duty at 5 to 6 percent, registration"
        f" fees, maintenance for 20 years, interest costs, and opportunity cost of the down payment."
        f"\n\nStep three: Run the honest 20 year comparison. Property appreciation at 6 percent"
        f" versus your monthly investment amount going into equity funds at 12 percent. Use an"
        f" online SIP calculator for the investment side."
        f"\n\nStep four: If buying, verify RERA registration of the project and builder, title"
        f" clarity, and all legal approvals. Never buy an unregistered project or one without OC."
        f"\n\nStep five: Ensure the EMI does not exceed 35 percent of your take-home income."
        f"\n\nIf you want real estate exposure through REITs for {subtopic}."
        f"\n\nStep one: Open or use your existing DEMAT account."
        f" Step two: Research Embassy Office Parks REIT, Mindspace Business Parks REIT, and"
        f" Brookfield India Real Estate Trust on NSE. Compare their distribution yields and"
        f" occupancy rates."
        f" Step three: Start with 15,000 to 25,000 rupees in one REIT and observe how it behaves."
        f" Step four: Add monthly or quarterly as part of your investment allocation."
        f"\n\nWhatever you choose, make it a data-driven decision. Real estate is not inherently"
        f" better or worse than other assets. The question is always what makes sense for your"
        f" specific situation, goals, and risk tolerance at this point in your life."
        f"\n\nIf this deep dive on {subtopic} helped you think more clearly about property"
        f" decisions, please give it a like and share it with someone who is currently making"
        f" a buy or rent decision."
        f"\n\nSubscribe to {CHANNEL_BRANDING} for daily finance education. See you tomorrow!"
    )
    sections = {"hook": hook, "problem": problem, "explanation": explanation,
                "example": example, "cta": cta}
    return {"title": title, "description": description, "sections": sections}


def _template_budgeting(subtopic: str) -> Dict[str, Any]:
    title = f"{subtopic} | Take Control of Your Money in 2025"
    description = (
        f"Master {subtopic} with this practical, India-focused guide. "
        "Step-by-step frameworks, real rupee examples, and tools to track every rupee "
        "so you can save more, stress less, and build real wealth."
    )
    hook = (
        f"Here is a number that should make every single person watching this video uncomfortable."
        f"\n\nResearch consistently shows that the majority of Indian households spending above"
        f" average incomes report that they feel like they do not have enough money. Meanwhile,"
        f" studies of genuinely wealthy individuals show that the majority achieved wealth on"
        f" moderate incomes by being exceptional at managing cash flow, not by earning unusually"
        f" high salaries."
        f"\n\nThe gap between these two groups is not income. It is systems. Specifically, it is"
        f" whether a person has a conscious, consistent, and effective system for managing their"
        f" money. In other words, it is {subtopic}."
        f"\n\nToday on {CHANNEL_BRANDING}, I am going to give you the complete framework for"
        f" {subtopic} designed specifically for Indian salaries, Indian expenses, and Indian"
        f" financial products."
        f"\n\nWe are going to cover three different budgeting frameworks so you can choose the"
        f" one that fits your personality and life stage. I am going to walk you through a real"
        f" example of how a Mumbai professional completely transformed her financial situation in"
        f" 12 months using nothing but {subtopic} and the same salary she had before. And I will"
        f" give you a specific 7-day implementation plan so that by this time next week, you"
        f" have a functioning system. Let us get into it right now."
    )
    problem = (
        f"Let me describe in very specific detail why most people struggle to build savings even"
        f" when they earn a decent income."
        f"\n\nThe problem is not that they are careless or irresponsible. The problem is that"
        f" they are trying to manage money manually in an environment that is specifically"
        f" engineered to make you spend as much as possible, as conveniently as possible."
        f"\n\nEvery UPI transaction is frictionless. Every app has a one-tap purchase. Every"
        f" food delivery platform sends you a notification when you are likely to be hungry."
        f" Every e-commerce site knows your purchasing history and serves you targeted deals."
        f" Every EMI is designed to make large purchases feel small by spreading them over months."
        f"\n\nThis is not a conspiracy. It is just the natural result of companies competing for"
        f" your spending. And without an equally deliberate system on your side, the default"
        f" outcome is that spending fills available income, savings never materialise, and"
        f" wealth never builds."
        f"\n\nThe specific pattern looks like this. Salary arrives. Essential bills are paid."
        f" Spending on lifestyle follows naturally because the money is there. By month end,"
        f" some unexpected expense always seems to appear. The savings plan gets pushed to next"
        f" month. Next month, the same thing happens."
        f"\n\nThis is not a character flaw. It is a system design flaw. And {subtopic} fixes"
        f" the design. The beautiful thing is that once you have the right system in place,"
        f" good financial outcomes become almost automatic."
    )
    explanation = (
        f"Let us go deep on {subtopic} with three complete frameworks you can implement today."
        f"\n\nFramework One: The 50-30-20 Rule."
        f" This is the simplest entry point into {subtopic}. Every rupee of take-home income"
        f" is allocated to one of three buckets."
        f"\n\nThe needs bucket receives 50 percent. This includes everything that is a"
        f" non-negotiable essential: rent or home loan EMI, electricity, gas, water, groceries,"
        f" internet and phone plan, health insurance premium, and transport to work. The critical"
        f" test for whether something belongs in needs is: would your basic life become"
        f" significantly harder without it?"
        f"\n\nThe wants bucket receives 30 percent. This covers lifestyle spending that you"
        f" choose but could live without: dining at restaurants, streaming services, gym"
        f" memberships, clothing beyond basics, hobbies, entertainment, travel, and social spending."
        f"\n\nThe future bucket receives 20 percent. This is your most important allocation."
        f" It covers emergency fund contributions, SIP investments, additional loan repayments"
        f" above the minimum, and long-term savings goals."
        f"\n\nThe power of the 50-30-20 rule for {subtopic} is its simplicity. You do not need"
        f" to track every individual rupee. You just need to monitor which bucket each major"
        f" expenditure falls into and ensure you never consistently overspend a bucket."
        f"\n\nIf your needs regularly exceed 50 percent, you have a structural problem: either"
        f" your income is not enough for your cost of living, or your fixed commitments are too"
        f" high relative to your income. This is the most important signal the 50-30-20 rule"
        f" gives you."
        f"\n\nFramework Two: Zero-Based Budgeting."
        f" This is a more rigorous approach to {subtopic}. At the start of every month, you"
        f" assign every single rupee of expected income to a specific purpose."
        f"\n\nExample: Income: 70,000 rupees."
        f" Rent: 18,000. Groceries: 8,000. Utilities: 3,000. Insurance: 2,000. Transport: 4,000."
        f" Dining out: 4,000. Shopping: 5,000. Entertainment: 2,000. Subscriptions: 1,500."
        f" SIP investment: 12,000. Emergency fund: 3,000. Loan overpayment: 2,500."
        f" Buffer for miscellaneous: 5,000. Total assigned: 70,000. Balance: zero."
        f"\n\nZero-based budgeting means zero unaccounted rupees, not zero savings. Every rupee"
        f" has a job. This approach is significantly more effective than trying to save what is"
        f" left over. The monthly process: on the 1st of the month, open your budgeting tool"
        f" and create the plan. Automate your investments and savings transfers on salary day."
        f" Track actual spending against the plan weekly. On the last day of the month, review."
        f"\n\nFramework Three: Pay Yourself First."
        f" This is the simplest and most powerful concept in all of {subtopic}. The principle"
        f" is that you save and invest before you do anything else. The moment your salary"
        f" arrives, an automatic transfer moves your pre-determined savings amount to a separate"
        f" account or investment. You then live on what remains."
        f"\n\nThe crucial mechanics: your SIP should deduct on salary day or one day after."
        f" Your emergency fund contribution should deduct the same day. You should never have"
        f" to consciously think about or decide whether to save. The automation does it for you"
        f" before the money is available for spending."
        f"\n\nMost people save what is left over. Wealthy people spend what is left after saving."
        f" This one inversion, combined with automation, is responsible for more Indian wealth"
        f" creation than any specific investment choice."
        f"\n\nTools for implementing {subtopic} in India."
        f" The Walnut app reads your bank SMS messages and automatically categorises your spending."
        f" Money Manager is an excellent manual tracking app with clean visualisations."
        f" Google Sheets with a simple custom template is free and infinitely customisable."
        f" Your bank's own UPI app analytics in PhonePe, Google Pay, and BHIM gives category"
        f" breakdowns of your spending automatically from transaction data."
    )
    example = (
        f"Let me show you {subtopic} in action through a real 12 month transformation example."
        f"\n\nNeha is a 29 year old HR professional in Delhi earning a take-home salary of"
        f" 65,000 rupees per month. She never tracked expenses deliberately and consistently"
        f" ran out of money by the 25th of each month. Here is what her spending actually looked"
        f" like before applying {subtopic}."
        f"\n\nHousing rent: 18,000 rupees."
        f" Groceries and household: 7,500 rupees."
        f" Food delivery Zomato and Swiggy: 8,200 rupees."
        f" Shopping clothing and Amazon: 9,500 rupees."
        f" Active subscriptions: 3,100 rupees, of which she was not actually using 1,400 rupees worth."
        f" Petrol plus Ola Uber: 5,500 rupees."
        f" Personal loan EMI: 6,000 rupees. Outstanding balance: 78,000 rupees at 18 percent interest."
        f" Miscellaneous including unknown impulse spending: 7,200 rupees."
        f" Total spending: 65,000 rupees. Net savings: zero."
        f"\n\nNeha applies {subtopic} using the zero-based budgeting framework."
        f"\n\nMonth one and two: emergency debt elimination mode."
        f" She cancels 1,400 rupees of unused subscriptions immediately."
        f" She reduces food delivery to 3,500 rupees by cooking more at home."
        f" She reduces shopping to 3,000 rupees."
        f" She directs 18,700 rupees per month toward loan overpayment."
        f" Loan cleared in less than 5 months instead of 13 months remaining on the original schedule."
        f" Interest saved: approximately 8,400 rupees."
        f"\n\nMonth three to seven: emergency fund building."
        f" Loan is cleared by month five. The 6,000 rupee EMI slot is now free."
        f" Plus the 12,700 she was overpaying. Total freed up: 18,700 rupees per month."
        f" She directs this entirely to a liquid fund emergency fund."
        f" By month seven, emergency fund reaches 1.2 lakh rupees."
        f"\n\nMonth eight onward: wealth building."
        f" Neha now has zero consumer debt and a growing emergency fund."
        f" She applies the 50-30-20 rule on a stabilised budget."
        f" Needs: 32,500 rupees. Wants: 13,000 rupees. Future: 19,500 rupees."
        f" Future allocation: SIP in Nifty 50 index fund 10,000, ELSS 5,000,"
        f" emergency fund top up 4,500."
        f"\n\nAt the end of 12 months."
        f" Personal loan: cleared."
        f" Emergency fund: 1.5 lakh rupees in liquid fund."
        f" SIP portfolio started: 50,000 rupees invested."
        f" Monthly savings rate: 30 percent of income."
        f" Projected portfolio at 35 on current trajectory: approximately 40 lakh rupees."
        f"\n\nSame salary. Completely different financial trajectory."
        f" The only variable was {subtopic}."
    )
    cta = (
        f"Here is your specific 7-day challenge to implement {subtopic} starting today."
        f"\n\nDay one: Download a budgeting app or open a Google Sheet. Choose one and set it up."
        f" The specific tool does not matter nearly as much as starting. Spend 20 minutes today."
        f"\n\nDay two: Pull up your last 3 months of bank statements or UPI transaction history."
        f" Write down your top 10 spending categories and the average monthly amount for each."
        f" Be honest. No category should be labelled miscellaneous. Name every rupee."
        f"\n\nDay three: Categorise every expense into needs, wants, or future savings. Calculate"
        f" what percentage of your income went to each. See where you stand relative to 50-30-20."
        f"\n\nDay four: Identify your top three spending leaks. These are categories where the"
        f" number surprised you or where you spent money without much conscious decision."
        f" Write them down."
        f"\n\nDay five: Set up your automated transfers. SIP deduct on salary day. Emergency"
        f" fund contribution deduct on salary day. These should require zero willpower to execute."
        f"\n\nDay six: Cancel every subscription you have not actively used in the past 30 days."
        f" Check your email for subscription receipts if you are unsure what you are paying for."
        f"\n\nDay seven: Write down your 6 month financial goals with specific numbers. How much"
        f" do you want in your emergency fund in 6 months? What do you want your monthly"
        f" investment amount to be in 6 months? Specific numbers make goals real."
        f"\n\n{subtopic} is the foundation of every other good financial decision. You cannot"
        f" invest effectively without it. You cannot eliminate debt without it. You cannot build"
        f" wealth without it. But once you have it, everything else becomes dramatically easier."
        f"\n\nPlease share this video with someone in your life who has been meaning to get their"
        f" finances in order. That could be the most valuable thing you do for them today."
        f"\n\nSubscribe to {CHANNEL_BRANDING} for a new finance video every single day."
        f" See you tomorrow. Stay financially disciplined!"
    )
    sections = {"hook": hook, "problem": problem, "explanation": explanation,
                "example": example, "cta": cta}
    return {"title": title, "description": description, "sections": sections}


# --------------- Dispatcher ---------------

_TEMPLATE_MAP = {
    "Stock Market Basics": _template_stock_market,
    "Mutual Funds": _template_mutual_funds,
    "Personal Finance": _template_personal_finance,
    "Tax Planning": _template_tax_planning,
    "Cryptocurrency": _template_crypto,
    "Real Estate": _template_real_estate,
    "Budgeting": _template_budgeting,
}


def generate_script(topic_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generate a full video script for the given topic.

    Args:
        topic_data: Output of topic_service.get_today_topic(), containing
                    category, subtopic, keywords.

    Returns:
        dict with title, description, tags, sections, full_text,
        word_count, duration_estimate_seconds.
    """
    category: str = topic_data["category"]
    subtopic: str = topic_data["subtopic"]

    template_fn = _TEMPLATE_MAP.get(category)
    if not template_fn:
        raise ValueError(f"No script template found for category: '{category}'")

    result = template_fn(subtopic)
    sections: Dict[str, str] = result["sections"]

    full_text = "\n\n".join([
        sections["hook"],
        sections["problem"],
        sections["explanation"],
        sections["example"],
        sections["cta"],
    ])

    word_count = len(full_text.split())
    duration_estimate = (word_count / TTS_WORDS_PER_MINUTE) * 60.0

    tags = _TAG_BANK.get(category, [])

    logger.info(
        "Script generated: '%s' | %d words | est. %.0f seconds (%.1f min)",
        subtopic,
        word_count,
        duration_estimate,
        duration_estimate / 60,
    )

    return {
        "title": result["title"],
        "description": result["description"],
        "tags": tags,
        "sections": sections,
        "full_text": full_text,
        "word_count": word_count,
        "duration_estimate_seconds": duration_estimate,
    }
